org: Unique Army
app: Mirage_App
service: scheduled-tg-bot
frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  environment:
    TELEGRAM_TOKEN: ${env:992176702:AAE62G_ubiBo1tGq8x0sQ2W2yYVtfRHBHxk}
functions:
  cron:
    handler: handler.send_message
    events:
      # Invoke Lambda function at 21:00 UTC every day
      - schedule: rate(1 minute)
